spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: 291197
    url: jdbc:postgresql://localhost:5432/tools_manager

authorization:
  email: ${AUTH_ADMIN_USER:admin@admin.com}
  password: ${AUTH_ADMIN_PASSWORD:admin}
  client:
    id: ${AUTH_CLIENT_ID:client-id}
    secret: ${AUTH_CLIENT_SECRET:client-secret}
    grant-types: ${AUTH_CLIENT_GRANT_TYPES:password, authorization_code, refresh_token, implicit}
    scopes: ${AUTH_CLIENT_SCOPES:read, write, trust}
